create table if not exists usuarios (
  id bigint generated by default as identity primary key,
  nombre text not null,
  correo text not null unique,
  password text not null,
  rol text not null check (rol in ('cliente', 'vendedor', 'administrador'))
);

create table if not exists productos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  precio numeric(10, 2) not null check (precio > 0),
  disponibilidad text not null default 'activo' check (disponibilidad in ('activo', 'no_activo'))
);

create table if not exists pedidos (
  id bigint generated by default as identity primary key,
  usuario_id bigint not null default 0,
  cliente text not null,
  estado text not null default 'pendiente' check (estado in ('pendiente', 'preparando', 'entregado', 'cancelado')),
  confirmacion text not null default 'aceptado' check (confirmacion in ('en_espera', 'aceptado', 'rechazado')),
  fecha_creacion text not null
);

create table if not exists detalle_pedidos (
  id bigint generated by default as identity primary key,
  pedido_id bigint not null,
  producto_id bigint not null,
  cantidad integer not null check (cantidad > 0),
  precio_unitario numeric(10, 2) not null check (precio_unitario > 0),
  observacion text not null default ''
);

create table if not exists entrenamiento_ia (
  id bigint generated by default as identity primary key,
  texto text not null,
  intencion text not null check (intencion in (
    'menu',
    'precio',
    'recomendacion',
    'pedido',
    'saludo',
    'total_pedido',
    'quitar_producto',
    'modificar_pedido',
    'confirmar_pedido',
    'cancelar_borrador'
  ))
);

insert into usuarios (nombre, correo, password, rol)
values
  ('Administrador', 'admin@cafeteria.com', 'admin123', 'administrador'),
  ('Vendedor', 'vendedor@cafeteria.com', 'vendedor123', 'vendedor')
on conflict (correo) do nothing;

alter table usuarios enable row level security;
alter table productos enable row level security;
alter table pedidos enable row level security;
alter table detalle_pedidos enable row level security;
alter table entrenamiento_ia enable row level security;

drop policy if exists "demo_usuarios_all" on usuarios;
drop policy if exists "demo_productos_all" on productos;
drop policy if exists "demo_pedidos_all" on pedidos;
drop policy if exists "demo_detalle_pedidos_all" on detalle_pedidos;
drop policy if exists "demo_entrenamiento_ia_all" on entrenamiento_ia;

create policy "demo_usuarios_all" on usuarios
for all using (true) with check (true);

create policy "demo_productos_all" on productos
for all using (true) with check (true);

create policy "demo_pedidos_all" on pedidos
for all using (true) with check (true);

create policy "demo_detalle_pedidos_all" on detalle_pedidos
for all using (true) with check (true);

create policy "demo_entrenamiento_ia_all" on entrenamiento_ia
for all using (true) with check (true);
